language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jcreinhold
  password:
    secure: qqGKcTUO6TartEGe+JwssnQlY9uZHV6MeBSg3TDOqFFqJWSiNgIWHu69E2ozmBtq28l7b5kveUbZEHGe2Q6pWyXie1Rp5YDCb5Xeo1fc7ahFbH2TNgYQmRMFugQxrpqdX+zqf/7XkZODLsL9FRGQBToySJ/EdjeLMQcpl6WCvEmj/z2e4006B7JG6i0gyU4hww1i8TYv6TmCd4jRoCWQYibxag0jeZJez3l1ytGOG76+Wamxbz7ko6UDY77eXYAdTq6lp1EXI+veiUNV1Jm52Xl4sfbsliZC+wgDx8Ti5oGeDMWvnRMHYUzuLBksvELJuY9I0J5SWpsUK2MQzgBctusM2k05tqeiaN2HIBsgQB6d4FTQxle+RxXB0e5VwImG8mvaBi1GsGqVGNh5bzbOPoZLY8kqQgw3hQ2GI2noDKE5h8/0EBNDOAMtz8TvFYIB0mCooaGR6hOXFpmRPvkdeZErj4xEJ7V9Q9L7NFPBf7y3p45SfZyLRoyTxXcdiyXgUk5hvNmgGWr8vZ0hsNpTHL+cLnEejcouAT7U3/x+5ZPaPb40m595kwSCRy0f1GE6jmIqI3RZSdFfMVBCxpebsoPEL22bxLThm5e82fD28izUzVPVpKML66Kkztq21iuLdavWoOutDGurKf6SOTugAS7BiZZUFOaXfl1MSAFsL+U=
  on:
    tags: true
    repo: jcreinhold/pyrobex
    python: 3.8
