language: python
python:
- 3.9
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: jmHTZj53zCeC80U8lWCBLgof83AB1fyFsvgtBAoMuSTCCzEdRohugZ4dsnLKW+KvNwYDTWHTJug4RTSbfPtQoba+NhdP9lOzS32Lit1L8XYQhdQbYfHsFlCKM/aN3zYsPa20C3Px/Lsz+cMR8R/Mgrdgln22scskWH9imGezKfNG5UIHjamXNNG8aFrKOEzCkRR8dbxjhPq83f9yRBu0EV/7iCmOAuLL9OLMlk/mb+DcV3TRiMFKh0TdSvYgJLLEHfDsWLtZucVgT9nq/iCcHmxBhZn8jj6W8+kHQ4j80k9EzosXjMACnpjxjxtMm6xXsR+f174xn6l8MBOw1k6hRW2v5DGNpF1twzTymn5yMbDrB6bBk7K1D7C2d7xvpITJmTL6TherzApu1UFX8k3Ur95b/caDGVPszUZ+sgV4OIRK9RF3oBb71530C9Fl7koBLK4oRArhWKPmEDdpdBdcTtx9bBkypsna17rpNHVWBbZSW6SaSEjievKLoO9Nxh3xPnQYwpTcpj/CdJzee8knNkBayLgmXZ7OF2TR1NvAvnGmZkyx/oBc2mqNki5tbrplSiU7/NvHxDGH6ER50thI36UGSzmLsOAVSqo63hbUz7griWpn050WrakvUvQGBL4qPksJiujMNSTV8erep9bwD+ayht7ZBc0nM8GbMcRlCwQ=
  on:
    tags: true
    repo: jcreinhold/pyrobex
    python: 3.8
